version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: nouislider
    versions:
    - 14.6.3
    - 14.6.4
  - dependency-name: intl-tel-input
    versions:
    - 17.0.11
    - 17.0.8
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
  - dependency-name: dompurify
    versions:
    - 2.2.6
